services:
  - type: web
    name: moked106
    runtime: python
    rootDir: app
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
